title: RunDocs
lang: en
description: Extends the continuous integration documentation capabilities of GitHub Pages for everyone!

remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock
